name: 'Perform string operations '
description: 'You will be perform string functions'
inputs:
  string_to_process:     
    required: true
    default: "Test"
  function_name:     
    required: true
    default: "Test"
outputs:
  result:
    description: 'converted string'  
runs:
  using: 'composite'
  steps:
    - run: |
        echo "Processing: ${{ inputs.string_to_process }}"         
        result=$(echo ${{ inputs.string_to_process }} | tr '[:lower:]' '[:upper:]')
        echo $result
        echo "result=$result" >> $GITHUB_OUTPUT
      shell: bash
